apiVersion: deployment.skyscanner.net/v1alpha1
kind: ProgressiveRollout
metadata:
  name: progressiverollout-sample
  namespace: argocd
spec:
  sourceRef:
    apiGroup: argoproj.io/v1alpha1
    kind: ApplicationSet
    name: appset-helm-dep
  stages:
    - name: eu-west-1a-1
      maxUnavailable: 1
      maxClusters: 1
      clusters:
        selector:
          matchLabels:
            name: eu-west-1a-1
