name: Release docker workflow

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:    
    - name: Build and push tagged docker image on master
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: maruina/argocd-progressive-rollout-controller
        tag: ${{ github.sha }}
